(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function n(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ba(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function ca(a){return a instanceof Array?a:ba(n(a))}var da={construct:"Metrika",callbackPostfix:"",version:"public",host:"mc.yandex.ru"};function ea(a,b){return b(a)}
function p(a){return function(b){return function(c){return a(b,c)}}}function fa(a){return function(b){return function(c){return a(c,b)}}}var ha=p(function(a,b){return a===b}),ia=p(ea);function r(){}function ja(a,b){if(!b||"function"!==typeof b)return!1;try{var c=""+b}catch(h){return!1}var d=c.length;if(d>35+a.length)return!1;for(var e=d-13,f=0,g=8;g<d;g+=1){f="[native code]"[f]===c[g]||7===f&&"-"===c[g]?f+1:0;if(12===f)return!0;if(!f&&g>e)break}return!1}function t(a,b){return ja(b,a)&&a}
function ka(a,b){for(var c=0;c<b.length;c+=1)if(b[c]===a)return c;return-1}var la;function ma(a){if(la)return la;var b=!1;try{b=[].indexOf&&0===[void 0].indexOf(void 0)}catch(d){}var c=a.Array&&a.Array.prototype&&t(a.Array.prototype.indexOf,"indexOf");return la=a=b&&c?function(d,e){return c.call(e,d)}:ka}var na=ma(window);function u(a){return a}function oa(a,b){return b}var pa=t(Array.from,"from");function qa(a){for(var b=a.length,c=[],d=0;d<b;d+=1)c.push(a[d]);return c}
function w(a){if(pa)try{return pa(a)}catch(b){}return qa(a)}function z(a,b){var c=[],d=[];var e=b?b:u;return function(){var f=w(arguments),g=e.apply(null,ca(f)),h=na(g,d);if(-1!==h)return c[h];f=a.apply(null,ca(f));c.push(f);d.push(g);return f}}var ra=/\./g;function sa(a){return"string"===typeof a}var ta=t(String.prototype.indexOf,"indexOf");function ua(a,b){for(var c=0,d=a.length-b.length,e=0;e<a.length;e+=1){c=a[e]===b[c]?c+1:0;if(c===b.length)return e-b.length+1;if(!c&&e>d)break}return-1}
var va=ta?function(a,b){return ta.call(a,b)}:ua;function wa(a,b){return va(a,b)}function xa(a,b){return!(!a||-1===va(a,b))}function ya(a){return a.replace(/\^/g,"\\^").replace(/\$/g,"\\$").replace(ra,"\\.").replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\|/g,"\\|").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/\?/g,"\\?").replace(/\*/g,"\\*").replace(/\+/g,"\\+").replace(/\{/g,"\\{").replace(/\}/g,"\\}")}var za=ha(null);function A(a){return"function"===typeof a}var C=ha(void 0);
function Aa(a){return C(a)||za(a)}function Ba(a){return!za(a)&&!C(a)&&"[object Object]"===Object.prototype.toString.call(a)}function Ca(a,b,c){b=void 0===b?[]:b;c=c||{};var d=b.length,e=a;A(e)&&(e="d",c[e]=a);var f;d?1===d?f=c[e](b[0]):2===d?f=c[e](b[0],b[1]):3===d?f=c[e](b[0],b[1],b[2]):4===d&&(f=c[e](b[0],b[1],b[2],b[3])):f=c[e]();return f}var Da=t(Function.prototype.bind,"bind");
function Ea(){var a=w(arguments);a=n(a);var b=a.next().value,c=a.next().value,d=ba(a);return function(){var e=[].concat(ca(d),ca(w(arguments)));if(Function.prototype.call)return Function.prototype.call.apply(b,[c].concat(ca(e)));if(c){for(var f="_b";c[f];)f+="_"+f.length;c[f]=b;e=c[f]&&Ca(f,e,c);delete c[f];return e}return Ca(b,e)}}var D=Da?function(){var a=w(arguments),b=n(a);a=b.next().value;var c=b.next().value;b=ba(b);return Da.apply(a,[c].concat(b))}:Ea;
function F(a,b){return D.apply(null,[b,null].concat(ca(a)))}function G(a,b){return D(b,null,a)}function Fa(a){return D(a.test,a)}var Ga=t(Array.prototype.reduce,"reduce");function Ha(a,b,c){for(var d=0,e=c.length;d<e;)b=a(b,c[d],d),d+=1;return b}var H=Ga?function(a,b,c){return Ga.call(c,a,b)}:Ha;function Ia(a,b){return F([a,b],H)}function I(){var a=w(arguments),b=a.shift();return function(){var c=b.apply(null,arguments);return H(ea,c,a)}}var Ja=p(F),Ka=Object.prototype.hasOwnProperty;
function La(a,b){return Aa(a)?!1:Ka.call(a,b)}function J(a,b){return a?H(function(c,d){if(Aa(c))return c;try{return c[d]}catch(e){}return null},a,b.split(".")):null}var K=fa(J),Ma=K("length");function Na(a){var b=void 0===b?{}:b;if(!a||1>a.length)return b;H(function(c,d,e){if(e===a.length-1)return c;e===a.length-2?c[d]=a[e+1]:La(c,d)||(c[d]={});return c[d]},b,a);return b}
function Oa(a,b){var c=J(b,a),d=J(b,"constructor.prototype."+a)||c;try{if(d&&d.apply)return function(){return d.apply(b,arguments)}}catch(e){return c}return d}function Pa(a,b,c){return c?a:b}var Qa=F([1,null],Pa),Ra=F([1,0],Pa),Sa=Boolean,Ta=t(Array.prototype.filter,"filter");function Ua(a,b){return Ha(function(c,d,e){a(d,e)&&c.push(d);return c},[],b)}var Va=Ta?function(a,b){return Ta.call(b,a)}:Ua,Wa=G(Sa,Va),Xa=t(Array.prototype.includes,"includes");
function Ya(a,b){return 1<=Ua(ha(a),b).length}var Za=Xa?function(a,b,c){return Xa.call(b,a,c)}:Ya,$a=fa(Za);function ab(a){return"[object Array]"===Object.prototype.toString.call(a)}var bb=t(Array.isArray,"isArray"),cb=bb?function(a){return bb(a)}:ab;function db(a){return a?cb(a)?a:pa?pa(a):"number"===typeof a.length&&0<=a.length?qa(a):[]:[]}
var eb=z(ma),fb=K("0"),gb=z(function(a){var b=J(a,"navigator")||{};a=J(b,"userAgent")||"";b=J(b,"vendor")||"";return{pb:-1<va(b,"Apple"),Db:a}}),hb=z(K("navigator.userAgent")),ib=/Firefox\/([0-9]+)/i,jb=z(function(a){var b=J(a,"document.documentElement.style"),c=J(a,"InstallTrigger");a=-1!==(J(a,"navigator.userAgent")||"").toLowerCase().search(ib);ib.lastIndex=0;return!(!(b&&"MozAppearance"in b)||Aa(c))||a});
function lb(){var a=Array.prototype.map;if(!jb(window))return!0;try{a.call({0:!0,length:-Math.pow(2,32)+1},function(){throw 1;})}catch(b){return!1}return!0}var mb=t(Array.prototype.map,"map");function nb(a,b){return H(function(c,d,e){c.push(a(d,e));return c},[],b)}var L=mb&&lb()?function(a,b){return b&&0<b.length?mb.call(b,a):[]}:nb,ob=p(L),pb=fa(L),qb=t(Array.prototype.some,"some");function rb(a,b){for(var c=0;c<b.length;c+=1)if(c in b&&a.call(b,b[c],c))return!0;return!1}
var sb=qb?function(a,b){return qb.call(b,a)}:rb,tb=t(Array.prototype.every,"every");function ub(a,b){return H(function(c,d,e){return c?!!a(d,e):!1},!0,b)}var vb=tb?function(a,b){return tb.call(b,a)}:ub;function wb(a,b){return a.isFinite(b)&&!a.isNaN(b)&&"[object Number]"===Object.prototype.toString.call(b)}var xb=fa(parseInt)(10),yb=t(Object.keys,"keys");function zb(a){var b=[],c;for(c in a)La(a,c)&&b.push(c);return b}var Ab=t(Object.entries,"entries");
function Bb(a){return C(a)?[]:Ha(function(b,c){b.push([c,a[c]]);return b},[],zb(a))}var Cb=Ab?function(a){return a?Ab(a):[]}:Bb,Db=yb?function(a){return yb(a)}:zb;function Eb(){var a=w(arguments),b=n(a);a=b.next().value;for(b=ba(b);b.length;){var c=b.shift(),d;for(d in c)La(c,d)&&(a[d]=c[d]);La(c,"toString")&&(a.toString=c.toString)}return a}
var O=Object.assign||Eb,Fb=p(function(a,b){return O({},a,b)}),Gb=z(I(hb,Fa(/ipad|iphone|ipod/i))),Hb=z(function(a){a=gb(a);var b=a.Db;return a.pb&&!b.match("CriOS")}),Ib=Fa(/Android.*Version\/[0-9][0-9.]*\sChrome\/[0-9][0-9.]|Android.*Version\/[0-9][0-9.]*\s(?:Mobile\s)?Safari\/[0-9][0-9.]*\sChrome\/[0-9][0-9.]*|; wv\).*Chrome\/[0-9][0-9.]*\sMobile/),Jb=Fa(/; wv\)/),Kb=z(function(a){a=hb(a);return Jb(a)||Ib(a)}),Lb=/Chrome\/(\d+)\./,Mb=z(function(a){return(a=(J(a,"navigator.userAgent")||"").match(Lb))&&
a.length?76<=xb(a[1]):!1}),Nb="other none unknown wifi ethernet bluetooth cellular wimax mixed".split(" "),Ob=z(function(a){var b=J(a,"navigator.connection.type");if(C(b))return null;a=eb(a)(b,Nb);return-1===a?b:""+a}),Pb=z(I(K("document.addEventListener"),function(a){return!a})),Qb=z(function(a){var b=J(a,"navigator")||{};return H(function(c,d){return c||J(b,d)},"",["language","userLanguage","browserLanguage","systemLanguage"])}),Rb=z(function(a){return(J(a,"top")||a)!==a}),Sb=z(K("top.contentWindow")),
Tb=z(function(a){var b=!1;try{b=a.navigator.javaEnabled()}catch(c){}return b});function Ub(a){return Za("prerender",L(G(J(a,"document"),J),["webkitVisibilityState","visibilityState"]))}
var Vb=z(function(a){var b=hb(a)||"",c=b.match(/Mac OS X ([0-9]+)_([0-9]+)/);c=c?[+c[1],+c[2]]:[0,0];b=b.match(/iPhone OS ([1-9]+)_([0-9]+)/);return 14<=(b?+b[1]:0)?!0:(Gb(a)||10<c[0]||10===c[0]&&13<=c[1])&&Hb(a)}),Wb=/Edg\/(\d+)\./,Xb=z(function(a){var b;if(!(b=Vb(a)))a:{if(jb(a)&&(b=hb(a).match(ib))&&b.length){b=68<=+b[1];break a}b=!1}if(!b)a:{if((a=hb(a))&&(a=a.match(Wb))&&1<a.length){b=79<=xb(a[1]);break a}b=!1}return b}),Yb=da.construct,Zb=da.host,$b=Pb(window),ac={Jb:24226447,Gb:26302566,Kb:51533966,
Hb:65446441,Ca:"https:",Ba:"25",Da:Yb,Xa:$b?512:2048,Va:$b?512:2048,Wa:$b?100:400,Ib:100,Za:"noindex"},bc=ha("1");function cc(a,b,c,d){var e={};return Ba(a)?a:(e.id=a,e.type=c,e.defer=d,e.params=b,e)}function dc(a){return H(function(b,c){var d=n(c),e=d.next().value,f=d.next().value;d=f.tb;f=a[f.ra];b[e]=d?d(f):f;return b},{},Cb(ec))}
var P=z(function(a){return a.id+":"+a.G}),Q=z(function(a){a=a.Ya=a.Ya||{};var b=a._metrika=a._metrika||{};return{Z:function(c,d){La(b,c)||(b[c]=d);return this},l:function(c,d){b[c]=d;return this},g:function(c,d){var e=b[c];return La(b,c)||C(d)?e:d}}}),fc=setTimeout;function gc(){}function hc(a,b){return function(){a.apply(b,arguments)}}
function R(a){if(!(this instanceof R))throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this.N=0;this.ya=!1;this.R=void 0;this.X=[];ic(a,this)}function jc(a,b){for(;3===a.N;)a=a.R;0===a.N?a.X.push(b):(a.ya=!0,R.za(function(){var c=1===a.N?b.vb:b.wb;if(null===c)(1===a.N?kc:lc)(b.promise,a.R);else{try{var d=c(a.R)}catch(e){lc(b.promise,e);return}kc(b.promise,d)}}))}
function kc(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");if(b&&("object"===typeof b||"function"===typeof b)){var c=b.then;if(b instanceof R){a.N=3;a.R=b;mc(a);return}if("function"===typeof c){ic(hc(c,b),a);return}}a.N=1;a.R=b;mc(a)}catch(d){lc(a,d)}}function lc(a,b){a.N=2;a.R=b;mc(a)}function mc(a){2===a.N&&0===a.X.length&&R.za(function(){a.ya||R.$a(a.R)});for(var b=0,c=a.X.length;b<c;b++)jc(a,a.X[b]);a.X=null}
function nc(a,b,c){this.vb="function"===typeof a?a:null;this.wb="function"===typeof b?b:null;this.promise=c}function ic(a,b){var c=!1;try{a(function(d){c||(c=!0,kc(b,d))},function(d){c||(c=!0,lc(b,d))})}catch(d){c||(c=!0,lc(b,d))}}R.prototype["catch"]=function(a){return this.then(null,a)};R.prototype.then=function(a,b){var c=new this.constructor(gc);jc(this,new nc(a,b,c));return c};
R.prototype["finally"]=function(a){var b=this.constructor;return this.then(function(c){return b.resolve(a()).then(function(){return c})},function(c){return b.resolve(a()).then(function(){return b.reject(c)})})};
R.all=function(a){return new R(function(b,c){function d(h,k){try{if(k&&("object"===typeof k||"function"===typeof k)){var l=k.then;if("function"===typeof l){l.call(k,function(m){d(h,m)},c);return}}e[h]=k;0===--f&&b(e)}catch(m){c(m)}}if(!a||"undefined"===typeof a.length)return c(new TypeError("Promise.all accepts an array"));var e=Array.prototype.slice.call(a);if(0===e.length)return b([]);for(var f=e.length,g=0;g<e.length;g++)d(g,e[g])})};
R.resolve=function(a){return a&&"object"===typeof a&&a.constructor===R?a:new R(function(b){b(a)})};R.reject=function(a){return new R(function(b,c){c(a)})};R.race=function(a){return new R(function(b,c){if(!a||"undefined"===typeof a.length)return c(new TypeError("Promise.race accepts an array"));for(var d=0,e=a.length;d<e;d++)R.resolve(a[d]).then(b,c)})};R.za="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){fc(a,0)};
R.$a=function(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)};var S=window.Promise,oc=t(S,"Promise"),pc=t(J(S,"resolve"),"resolve"),qc=t(J(S,"reject"),"reject"),rc=t(J(S,"all"),"all");if(oc&&pc&&qc&&rc){var sc=function(a){return new Promise(a)};sc.resolve=D(pc,S);sc.reject=D(qc,S);sc.all=D(rc,S);S=sc}else S=R;var tc=["http.0.st..rt.","network error occurred","send beacon","Content Security Policy","DOM Exception 18"],uc;
function vc(a){this.message=a}var wc=function(a){return function(b,c){c=void 0===c?!1:c;if(uc)var d=new uc(b);else ja("Error",a.Error)?(uc=a.Error,d=new a.Error(b)):(uc=vc,d=new uc(b));c&&(d.unk=!0);return d}}(window);function xc(a){return wc("http."+a.status+".st."+a.statusText+".rt."+(""+a.responseText).substring(0,50))}var yc=Fa(/^http./);function zc(a){throw a;}function Ac(a,b){for(var c="",d=0;d<b.length;d+=1)c+=""+(d?a:"")+b[d];return c}
var Bc=t(Array.prototype.join,"join"),T=Bc?function(a,b){return Bc.call(b,a)}:Ac,Cc=p(T),Dc=z(function(a){a=!(!a.addEventListener||!a.removeEventListener);return{Ab:a,C:a?"addEventListener":"attachEvent",ga:a?"removeEventListener":"detachEvent"}});function Ec(a,b,c,d,e,f){a=Dc(a);var g=a.C,h=a.ga;f=f?h:g;if(b[f])if(a.Ab)if(e)b[f](c,d,e);else b[f](c,d);else b[f]("on"+c,d)}
var Fc=z(function(a){var b=!1;if(!a.addEventListener)return b;try{var c=Object.defineProperty({},"passive",{get:function(){b=!0;return 1}});a.addEventListener("test",r,c)}catch(d){}return b}),Hc=p(function(a,b){if(null!==b)return a?O({capture:!0,passive:!0},b||{}):!!b}),Ic=z(function(a){var b=Fc(a),c=Hc(b),d={};return O(d,{C:function(e,f,g,h){L(function(k){var l=c(h);Ec(a,e,k,g,l,!1)},f);return D(d.ua,d,e,f,g,h)},ua:function(e,f,g,h){L(function(k){var l=c(h);Ec(a,e,k,g,l,!0)},f)}})});
function Jc(a){return J(a,"performance")||J(a,"webkitPerformance")}function Kc(a){a=Jc(a);var b=J(a,"timing.navigationStart"),c=J(a,"now");c&&(c=D(c,a));return[b,c]}function Lc(a,b){var c=n(b||Kc(a)),d=c.next().value;c=c.next().value;return!isNaN(d)&&A(c)?Math.round(c()+d):a.Date.now?a.Date.now():(new a.Date).getTime()}function Mc(a){return(10>a?"0":"")+a}
function Nc(a){var b=Ic(a),c=Kc(a),d={J:a,va:0,sa:c,Pb:Lc(a,c)},e=n(c);c=e.next().value;e=e.next().value;c&&e||b.C(a,["beforeunload","unload"],function(){0===d.va&&(d.va=Lc(a,d.sa))});return ia(d)}function U(a){var b=a.va;return 0!==b?b:Lc(a.J,a.sa)}function Oc(a){return Math.round(U(a)/1E3)}var V=z(Nc);function Pc(a){return a.ta||a.ea.length<=a.L}function Qc(a){a.L=a.ea.length}function Rc(a){a.ta=!0}function Sc(a){a.ta=!1}function Tc(a){Pc(a)&&zc(wc("i"));var b=a.Ha(a.ea[a.L]);a.L+=1;return b}
var Uc=p(function(a,b){for(var c=[];!Pc(b);){var d=Tc(b);a(d,function(e){return e(b)});c.push(d)}return c});function Vc(a,b){return function(c){var d=V(a),e=d(U);return Uc(function(f,g){d(U)-e>=b&&g(Rc)})(c)}}function Wc(a){for(var b=!0,c={};!Pc(a)&&b;)b=!1,c.aa=function(){b=!0;a.L+=1},a.Ha(a.ea[a.L],function(d){return function(){d.aa()}}(c)),b||(a.L+=1,c.aa=G(a,Wc)),c={aa:c.aa}}function Xc(a,b){return ia({ea:a,Ha:b||u,ta:!1,L:0})}
function Yc(a,b,c){c=void 0===c?!1:c;return new S(function(d,e){function f(k,l){l();d()}var g=a.slice();g.push({I:f,T:f});var h=Xc(g,function(k,l){var m=c?k.I:k.T;if(m)try{m(b,l)}catch(q){h(Qc),e(q)}else l()});h(Wc)})}function Zc(a){try{return encodeURIComponent(a)}catch(b){}a=T("",Va(function(b){return 55296>=b.charCodeAt(0)},a.split("")));return encodeURIComponent(a)}function $c(a){var b="";try{b=decodeURIComponent(a)}catch(c){}return b}
function ad(a){return a?I(ob(function(b){var c=n(b.split("="));b=c.next().value;c=c.next().value;return[b,Aa(c)?void 0:$c(c)]}),Ia(function(b,c){var d=n(c),e=d.next().value;d=d.next().value;b[e]=d;return b},{}))(a.split("&")):{}}function bd(a){return a?I(Cb,Ia(function(b,c){var d=n(c),e=d.next().value;d=d.next().value;C(d)||Aa(d)||b.push(e+"="+Zc(d));return b},[]),Cc("&"))(a):""}function cd(a,b,c){var d=C(c);C(b)&&d?(d=1,b=1073741824):d?d=1:(d=b,b=c);return a.Math.floor(a.Math.random()*(b-d))+d}
function dd(a,b,c){return function(){var d=Q(arguments[0]),e=c?"global":"m25",f=d.g(e,{}),g=J(f,a);g||(g=z(b),f[a]=g,d.l(e,f));return g.apply(null,arguments)}}var ed=$a([26812653]),fd=z(I(K("id"),ed),P),gd="hash host hostname href pathname port protocol search".split(" ");function W(a){return H(function(b,c){var d=J(a,"location."+c);b[c]=d?""+d:"";return b},{},gd)}
var hd="ru by kz az kg lv md tj tm uz ee fr lt com co.il com.ge com.am com.tr com.ru".split(" "),id=/(?:^|\.)(?:(ya\.ru)|(?:yandex)\.(\w+|com?\.\w+))$/,jd=z(function(a){return(a?a.replace(/^www\./,""):"").toLowerCase()}),kd=z(function(a){a=W(a).hostname;var b=!1;a&&(b=-1!==a.search(id));return b}),ld=I(W,K("protocol"),ha("https:")),md=z(function(a){return Mb(a)&&ld(a)?"SameSite=None;Secure;":""}),nd=/^\s+|\s+$/g,od=t(String.prototype.trim,"trim");
function pd(a,b){if(a){var c=od?od.call(a):(""+a).replace(nd,"");return b&&c.length>b?c.substring(0,b):c}return""}var qd=p(function(a,b){return b.replace(a,"")}),rd=qd(/\D/g),sd=["metrika_enabled"],td=[];function ud(a,b){var c=vd;return!td.length||Za(b,sd)?!0:H(function(d,e){return d&&e(a,c,b)},!0,td)}
function wd(a){try{var b=a.document.cookie;if(!Aa(b)){var c={};L(function(d){var e=n(d.split("="));d=e.next().value;e=e.next().value;c[pd(d)]=pd($c(e))},(b||"").split(";"));return c}}catch(d){}return null}var xd=dd("gsc",wd);function vd(a,b){var c=xd(a);return c?c[b]||null:null}var yd=/:\d+$/;
function zd(a,b,c,d,e,f,g){g=void 0===g?!1:g;if(ud(a,b)){var h=b+"="+encodeURIComponent(c)+";";h+=""+md(a);if(d){var k=new Date;k.setTime(k.getTime()+6E4*d);h+="expires="+k.toUTCString()+";"}e&&(d=e.replace(yd,""),h+="domain="+d+";");try{a.document.cookie=h+("path="+(f||"/")),g||(xd(a)[b]=c)}catch(l){}}}
var Ad=z(function(a){var b=(W(a).host||"").split(".");return 1===b.length?b[0]:H(function(c,d,e){e+=1;2<=e&&!c&&(e=T(".",b.slice(-e)),zd(a,"metrika_enabled","1",0,e,void 0,!0),(d=(d=wd(a))&&d.metrika_enabled)&&zd(a,"metrika_enabled","",-100,e,void 0,!0),d&&(c=e));return c},"",b)}),Bd=z(function(a,b,c){b=void 0===b?"_ym_":b;c=void 0===c?"":c;var d=Ad(a),e=1===(d||"").split(".").length?d:"."+d,f=c?"_"+c:"";return{Ea:function(g,h,k){zd(a,""+b+g+f,"",-100,h||e,k,!1);return this},g:function(g){return vd(a,
""+b+g+f)},l:function(g,h,k,l,m){zd(a,""+b+g+f,h,k,l||e,m);return this}}}),Cd=z(function(a){var b=Bd(a),c="1"===b.g("debug"),d=-1<wa(W(a).href,"_ym_debug=1")||-1<wa(W(a).href,"_ym_debug=2"),e=a._ym_debug;!e&&!d||c||(a=W(a),b.l("debug","1",void 0,a.host));return!!(c||e||d)});function Dd(){return{}}function Ed(){return[]}var Fd=dd("debuggerEvents",Ed,!0);
function Gd(a,b){if(Cd(a)){var c=b.counterKey;if(c){var d=n(c.split(":"));c=d.next().value;d=d.next().value;try{var e=parseInt(c,10)}catch(f){e=null}e=ed(e);if("1"===d||e)return}e=Fd(a);1E3===e.length&&e.shift();e.push(b)}}function Hd(a,b,c){var d=cd(a),e=c.O,f=c.F,g=c.V,h=c.W;c=c.xa;var k={},l={},m={};Gd(a,(m.name="request",m.data=(l.url=b,l.requestId=d,l.senderParams=(k.rBody=f,k.debugStack=e,k.rHeaders=g,k.rQuery=h,k.verb=c,k),l),m));return d}var Id=t(Array.prototype.find,"find");
function Jd(a,b){for(var c=0;c<b.length;c+=1)if(a.call(b,b[c],c))return b[c]}var Kd=Id?function(a,b){return Id.call(b,a)}:Jd,Ld=p(function(a,b){var c=b||{};return{J:G(c,u),g:function(d,e){var f=c[d];return C(f)&&!C(e)?e:f},l:function(d,e){c[d]=e;return this},Oa:function(d,e){return""===e||Aa(e)?this:this.l(d,e)},zb:G(c,a)}})(function(a){var b="";a=H(function(c,d){var e=n(d),f=e.next().value;e=e.next().value;e=""+f+":"+e;"t"===f?b=e:c.push(e);return c},[],Cb(a));b&&a.push(b);return T(":",a)});
function Md(a,b){var c=O({},b.m),d=V(a);b.o&&(c["browser-info"]=Ld(b.o.J()).l("st",d(Oc)).zb());return c}
function Nd(a,b,c,d,e,f){e=void 0===e?0:e;f=void 0===f?0:f;var g=O({O:[]},d.H),h=n(b[f]),k=h.next().value;h=h.next().value;var l=c[e];if((!g.V||!g.V["Content-Type"])&&g.F){var m={};g.V=O({},g.V,(m["Content-Type"]="application/x-www-form-urlencoded",m));g.F="site-info="+Zc(g.F)}g.xa=g.F?"POST":"GET";g.W=Md(a,d);g.P=(d.ia||{}).P;g.O.push(k);O(d.H,g);k=""+l+(d.ha&&d.ha.sb?"/1":"");var q=0;q=Hd(a,k,g);return h(k,g).then(function(y){var B=q,x={},v={};Gd(a,(v.name="requestSuccess",v.data=(x.body=y,x.requestId=
B,x),v));return{yb:y,Cb:e}})["catch"](function(y){var B=q,x={},v={};Gd(a,(v.name="requestFail",v.data=(x.error=y,x.requestId=B,x),v));B=f+1>=b.length;x=e+1>=c.length;B&&x&&zc(y);return Nd(a,b,c,d,!x&&B?e+1:e,B?0:f+1)})}function Od(a,b){return function(c,d){return Nd(a,b,d,c)}}function Pd(a,b){L(I(u,D(a.push,a)),b);return a}function Qd(a,b){return b?a(b):a()}
var Rd={id:"id",Ua:"ut",G:"type",oa:"ldc",qa:"nck",na:"url",kb:"referrer"},Sd=/^\d+$/,Td={id:function(a){a=""+(a||"0");Sd.test(a)||(a="0");try{var b=xb(a)}catch(c){b=0}return b},G:function(a){return""+(a||0===a?a:"0")},qa:Sa,Ua:Sa};Rd.ka="defer";Td.ka=Sa;Rd.D="params";Td.D=function(a){return Ba(a)||cb(a)?a:null};Rd.wa="userParams";Rd.Sa="triggerEvent";Td.Sa=Sa;Rd.Na="sendTitle";Td.Na=function(a){return!!a||C(a)};Rd.Ra="trackLinks";
var ec=H(function(a,b){var c=n(b),d=c.next().value;c=c.next().value;a[d]={ra:c,tb:Td[d]};return a},{},Cb(Rd));function Ud(a){return H(function(b,c){var d=n(c),e=d.next().value;d=d.next().value;b[ec[e].ra]=d;return b},{},Cb(a))}function Vd(a,b,c){for(var d=[b,c],e=-1E4,f=0;f<a.length;f+=1){var g=n(a[f]),h=g.next().value;g=g.next().value;if(c===g&&h===b)return;if(c<g&&c>=e){a.splice(f,0,d);return}e=g}a.push(d)}
var Wd={},Xd=(Wd.w=[[function(a,b){return{I:function(c,d){var e=c.m,f={};e=(f["page-url"]=e&&e["page-url"]||"",f.charset="utf-8",f);"0"!==b.G&&(e["cnt-class"]=b.G);c.o||(c.o=Ld());f=c.o;e={ia:{P:"watch/"+b.id},H:O(void 0===c.H?{}:c.H,{ja:!!f.g("pv")&&!f.g("ar")&&!f.g("wh")}),m:O(c.m||{},e)};O(c,e);d()}}},1]],Wd);
function Yd(a,b,c){var d=Od(a,b);return function(e){return Yc(c,e,!0).then(function(){var f=e.ia||{},g=void 0===f.lb?"":f.lb,h=void 0===f.P?"":f.P;f=L(function(k){return ac.Ca+"//"+(""+g+k||Zb)+"/"+h},void 0===f.mb?[Zb]:f.mb);return d(e,f)}).then(function(f){var g=f.yb;f=f.Cb;e.Sb=g;e.Tb=f;return Yc(c,e).then(G(g,u))})}}function Zd(a){return function(b,c,d){return function(e,f){var g=L(I(fb,Ja([b,f]),Qd),Xd[a]||[]);g=Pd(g,d);return Yd(b,c,g)(e)}}}var $d=Zd("w"),ae=["webkitvisibilitychange","visibilitychange"];
function be(a){return{I:function(b,c){var d=a.document,e=b.o;if(e&&Ub(a)){var f=Ic(a),g=function(h){Ub(a)||(f.ua(d,ae,g),c());return h};f.C(d,ae,g);e.l("pr","1")}else c()}}}function ce(a){var b="";cb(a)?b=T(".",a):sa(a)&&(b=a);return wc("err.kn("+ac.Ba+")"+b)}function de(){var a=w(arguments);zc(ce(a))}var ee=Fa(/^err.kn/),fe=[];
function ge(a,b,c){var d="u.a.e",e="";c&&("object"===typeof c?(c.unk&&zc(c),d=c.message,e="string"===typeof c.stack&&c.stack.replace(/\n/g,"\\n")||"n.s.e.s"):d=""+c);ee(d)||sb(G(d,xa),tc)||yc(d)&&.1<=a.Math.random()||L(I(u,Ja(["jserrs",d,b,e]),Qd),fe)}function X(a,b,c,d){var e=c||zc;return function(){var f=d;try{f=e.apply(null,arguments)}catch(g){ge(a,b,g)}return f}}function Y(a,b,c){return function(){return X(arguments[0],a,b,c).apply(this,arguments)}}
var he="A B BIG BODY BUTTON DD DIV DL DT EM FIELDSET FORM H1 H2 H3 H4 H5 H6 HR I IMG INPUT LI OL P PRE SELECT SMALL SPAN STRONG SUB SUP TABLE TBODY TD TEXTAREA TFOOT TH THEAD TR U UL ABBR AREA BLOCKQUOTE CAPTION CENTER CITE CODE CANVAS DFN EMBED FONT INS KBD LEGEND LABEL MAP OBJECT Q S SAMP STRIKE TT ARTICLE AUDIO ASIDE FOOTER HEADER MENU METER NAV PROGRESS SECTION TIME VIDEO NOINDEX NOBR MAIN svg circle clippath ellipse defs foreignobject g glyph glyphref image line lineargradient marker mask path pattern polygon polyline radialgradient rect set text textpath title".split(" "),ie=
[],je=/^\s*(data|javascript):/i,ke=new RegExp(T("",["\\.("+T("|","3gp 7z aac ac3 acs ai avi ape apk asf bmp bz2 cab cdr crc32 css csv cue divx dmg djvu? doc(x|m|b)? emf eps exe flac? flv iso swf gif t?gz jpe?g? js m3u8? m4a mp(3|4|e?g?) m4v md5 mkv mov msi ods og(g|m|v) psd rar rss rtf sea sfv sit sha1 svg tar tif?f torrent ts txt vob wave? wma wmv wmf webm ppt(x|m|b)? xls(x|m|b)? pdf phps png xpi g?zip".split(" "))+")$"]),"i"),le={};
function me(a,b){if(!b)return null;try{return a.JSON.parse(b)}catch(c){return null}}function ne(a,b){try{return a.JSON.stringify(b,null,void 0)}catch(c){return null}}function oe(a){try{return a.localStorage}catch(b){}return null}function pe(a,b){var c=oe(a);try{c.removeItem(b)}catch(d){}}function qe(a,b){var c=oe(a);try{return me(a,c.getItem(b))}catch(d){}return null}function re(a,b,c){var d=oe(a);a=ne(a,c);if(!za(a))try{d.setItem(b,a)}catch(e){}}
var se=z(function(a){re(a,"_ymBRC","1");var b="1"!==qe(a,"_ymBRC");b||pe(a,"_ymBRC");return b});function te(a,b,c){var d=""+(void 0===c?"_ym":c)+(void 0===b?"":b);d&&(d+="_");return{qb:se(a),g:function(e,f){var g=qe(a,""+d+e);return za(g)&&!C(f)?f:g},l:function(e,f){re(a,""+d+e,f);return this},Ea:function(e){pe(a,""+d+e);return this}}}
var ue=z(te),ve=z(te,function(a,b,c){return""+b+c}),we=z(function(a){a=J(a,"document")||{};return(""+(a.characterSet||a.charset||"")).toLowerCase()}),xe=z(I(K("document"),G("createElement",Oa)));function ye(a){var b=a&&a.parentNode;b&&b.removeChild(a)}function ze(a,b){try{return(new RegExp("(?:^|\\s)"+a+"(?:\\s|$)")).test(b.className)}catch(c){return!1}}
var Ae=z(function(a){var b=J(a,"Element.prototype");return b?(a=Kd(function(c){var d=b[c];return!!d&&ja(c,d)},["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"]))?b[a]:null:null});function Ce(a){a=J(a,"document");try{return a.getElementsByTagName("body")[0]}catch(b){return null}}function De(a){var b=J(a,"document")||{},c=b.documentElement;return"CSS1Compat"===b.compatMode?c:Ce(a)||c}
function Ee(a,b,c){c=Oa("dispatchEvent",c||a.document);var d=null,e=J(a,"Event.prototype.constructor");if(e&&(ja("(Event|Object|constructor)",e)||Pb(a)&&"[object Event]"===""+e))try{d=new a.Event(b)}catch(f){if((a=Oa("createEvent",J(a,"document")))&&A(a)){try{d=a(b)}catch(g){}d&&d.initEvent&&d.initEvent(b,!1,!1)}}d&&c(d)}function Fe(a){if(a)try{var b=a.nodeName;if(sa(b))return b;b=a.tagName;if(sa(b))return b}catch(c){}}var Ge=ha("INPUT"),He=I(Fe,Ge),Ie=/\/$/;
function Je(a){var b=Q(a),c=b.g("hitId");c||(c=cd(a),b.l("hitId",c));return c}function Ke(a,b){var c=ue(a),d=Bd(a),e=b.oa||"uid";return[c.g(e),d.g(e)]}var Le=dd("r",function(a,b){var c=n(Ke(a,b)),d=c.next().value;return!c.next().value&&d});
function Me(a,b){var c=b.oa,d=c||"uid";c=c?a.location.hostname:void 0;var e=Bd(a),f=ue(a),g=V(a)(Oc),h=n(Ke(a,b)),k=h.next().value;h=h.next().value;var l=e.g("d");Le(a,b);var m=!1;!h&&k&&(h=k,m=!0);if(!h)h=T("",[g,cd(a,1E6,999999999)]),m=!0;else if(!l||15768E3<g-xb(l))m=!0;m&&!b.qa&&(e.l(d,h,525600,c),e.l("d",""+g,525600,c));f.l(d,h);return h}function Ne(a,b,c){return Oa("setTimeout",a)(b,c)}function Oe(a,b){return Oa("clearTimeout",a)(b)}
function Pe(a,b,c,d){return Ne(a,X(a,"d.err."+(d||"def"),b),c)}function Qe(a,b){return function(c){return c(a,b)}}function Re(a){function b(e){J(c,d)?e():Pe(a,G(e,b),100)}var c=void 0===c?a:c;var d=(c.nodeType?"contentWindow.":"")+"document.body";return ia(function(e,f){b(f)})}function Se(a){var b=[],c={Qb:b};c.C=I(D(b.push,b),G(c,u));c.ga=I(fa(ma(a))(b),fa(D(b.splice,b))(1),G(c,u));c.M=I(u,fa(Qd),pb(b));return c}
function Te(a){var b={};return{C:function(c,d){L(function(e){J(b,e)||(b[e]=Se(a));b[e].C(d)},c);return this},ga:function(c,d){L(function(e){J(b,e)&&b[e].ga(d)},c);return this},M:function(c,d){return J(b,c)?X(a,"e."+c,b[c].M,[])(d):[]}}}var Ue=z(function(){return{S:{},pending:{},children:{}}}),Ve=K("postMessage");
function We(a,b){return function(c,d){var e={ma:V(a)(U),key:a.Math.random(),dir:0};c.length&&(e.ma=xb(c[0]),e.key=parseFloat(c[1]),e.dir=xb(c[2]));O(d,b);var f={};f=(f.data=d,f.__yminfo=T(":",["__yminfo",e.ma,e.key,e.dir]),f);return{Ia:e,Qa:ne(a,f)||""}}}var Xe=Y("s.f",function(a,b,c,d,e){b=b(d);var f=Ue(a),g=T(":",[b.Ia.ma,b.Ia.key]);if(Ve(c)){f.pending[g]=e;try{c.postMessage(b.Qa,"*")}catch(h){delete f.pending[g];return}Pe(a,function(){delete f.pending[g]},5E3,"if.s")}});
function Ye(a){if(ja("MutationObserver",a.MutationObserver)){var b=Ue(a).children,c=new a.MutationObserver(function(){L(function(d){J(b[d],"window.window")||delete b[d]},Db(b))});Re(a)(Qe(r,function(){c.observe(a.document.body,{subtree:!0,childList:!0})}))}}
function Ze(a,b){var c=Ue(a);b.C(["initToParent"],function(d){var e=n(d);d=e.next().value;e=e.next().value;window.window&&(c.children[e.counterId]={info:e,window:d.source})}).C(["initToChild"],function(d){var e=n(d);d=e.next().value;e=e.next().value;d.source===a.parent&&b.M("parentConnect",[d,e])}).C(["parentConnect"],function(d){var e=n(d);d=e.next().value;e=e.next().value;e.counterId&&(c.S[e.counterId]={info:e,window:d.source})})}
var $e=Y("s.fh",function(a,b,c,d,e,f){var g=null,h=null,k=Ue(a),l=null;try{g=me(a,f.data),h=g.__yminfo,l=g.data}catch(m){return}if(!Aa(h)&&h.substring&&"__yminfo"===h.substring(0,8)&&!Aa(l)&&(a=h.split(":"),4===a.length))if(g=b.id,h=n(a),h.next(),b=h.next().value,a=h.next().value,h=h.next().value,!cb(l)&&l.type&&"0"===h&&l.counterId){if(!l.toCounter||l.toCounter==g){k=null;try{k=f.source}catch(m){}!za(k)&&Ve(k)&&(f=d.M(l.type,[f,l]),e=L(I(u,Fb(e)),f.concat([void 0])),l=c([b,a,l.counterId],e),k.postMessage(l.Qa,
"*"))}}else h===""+g&&cb(l)&&Va(function(m){return!(!m.hid||!m.counterId)},l).length===l.length&&(c=k.pending[T(":",[b,a])])&&c.apply(null,[f].concat(l))}),af=z(function(a,b){var c=Oa("getElementsByTagName",J(a,"document")),d=Ue(a),e=Ve(a),f=Te(a),g=Ic(a);if(!c||!e)return null;c=c.call(a.document,"iframe");e={};e=(e.counterId=b.id,e.hid=""+Je(a),e);Xb(a)&&(e.duid=Me(a,b));Ze(a,f);Ye(a);var h=We(a,e),k=F([a,G([],h)],Xe);L(function(l){var m=null;try{m=l.contentWindow}catch(q){}m&&k(m,{type:"initToChild"},
function(q,y){f.M("initToParent",[q,y])})},c);Rb(a)&&k(a.parent,{type:"initToParent"},function(l,m){f.M("parentConnect",[l,m])});g.C(a,["message"],F([a,b,h,f,e],$e));return{gb:f,S:d.S,children:d.children,Ub:k}},I(oa,P)),bf=z(function(a,b){if(!Xb(a)||!Rb(a))return Me(a,b);var c=af(a,b);return c&&c.S[b.id]?c.S[b.id].info.duid||Me(a,b):Me(a,b)},function(a,b){return""+b.oa+b.qa}),cf=z(I(V,ia(function(a){return-(new a.J.Date).getTimezoneOffset()}))),df=I(V,ia(function(a){a=new a.J.Date;return T("",L(Mc,
[a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds()]))})),ef=I(V,ia(Oc)),ff=z(I(V,ia(function(a){return n(a.sa).next().value}))),gf=z(function(a){a=Q(a);var b=a.g("counterNum",0)+1;a.l("counterNum",b);return b},I(oa,P)),Z={},hf=(Z.vf=G(da.version,u),Z.nt=Ob,Z.fu=function(a,b,c){var d=c.m;if(!d)return null;b=(J(a,"document.referrer")||"").replace(Ie,"");c=(d["page-ref"]||"").replace(Ie,"");d=d["page-url"];a=W(a).href!==d;b=b!==c;c=0;a&&b?c=3:b?c=1:a&&(c=2);return c},
Z.en=we,Z.la=Qb,Z.ut=function(a,b,c){var d=c.B;c=c.m;d=d&&d.fa;c&&(kd(a)||b.Ua||d)&&(c.ut=ac.Za);return null},Z.v=G(ac.Ba,u),Z.cn=gf,Z.dp=function(a){var b=Q(a),c=b.g("bt",{});if(C(b.g("bt"))){var d=J(a,"navigator.getBattery");try{c.p=d&&d.call(a.navigator)}catch(e){}b.l("bt",c);c.p&&c.p.then&&c.p.then(X(a,"bi:dp.p",function(e){c.Eb=J(e,"charging")&&0===J(e,"chargingTime")}))}return Ra(c.Eb)},Z.ls=z(function(a,b){var c=ve(a,b.id),d=V(a),e=c.g("lsid");return+e?e:(d=cd(a,0,d(U)),c.l("lsid",d),d)},oa),
Z.hid=Je,Z.phid=function(a,b){if(!Rb(a))return null;var c=af(a,b);if(!c)return null;var d=Db(c.S);return d.length?c.S[d[0]].info.hid:null},Z.z=cf,Z.i=df,Z.et=ef,Z.c=I(K("navigator.cookieEnabled"),Qa),Z.rn=I(u,cd),Z.rqn=function(a,b,c){c=c.m;if(!c||c.nohit)return null;b=P(b);a=ve(a,b);b=(a.g("reqNum",0)||0)+1;a.l("reqNum",b);if(a.g("reqNum")===b)return b;a.Ea("reqNum");return null},Z.u=bf,Z.w=function(a){var b=J(a,"visualViewport.width");var c=J(a,"visualViewport.height"),d=J(a,"visualViewport.scale");
(b=Aa(b)||Aa(c)?null:[Math.floor(b),Math.floor(c),d])?(d=n(b),b=d.next().value,c=d.next().value,d=d.next().value,a=[a.Math.round(b*d),a.Math.round(c*d)]):(b=De(a),a=[J(b,"clientWidth")||a.innerWidth,J(b,"clientHeight")||a.innerHeight]);b=n(a);a=b.next().value;b=b.next().value;return a+"x"+b},Z.s=function(a){var b=J(a,"screen");if(b){a=J(b,"width");var c=J(b,"height");b=J(b,"colorDepth")||J(b,"pixelDepth");return T("x",[a,c,b])}return null},Z.sk=K("devicePixelRatio"),Z.ifr=I(Rb,Qa),Z.j=I(Tb,Qa),Z.sti=
function(a){return Rb(a)&&Sb(a)?"1":null},Z),jf=z(function(){return Pd(Db(hf),Db(le))});function kf(){return function(a,b){return{I:function(c,d){var e=c.o,f=c.m;e&&f&&L(function(g){var h=hf[g];h&&(h=Y("bi:"+g,h,null)(a,b,c),e.Oa(g,h))},jf());d()}}}}var lf=z(Dd,P);function mf(a,b,c){if(Xb(a)&&Rb(a)){var d=lf(b);if(!d.rb){d.rb=!0;b=af(a,b);if(!b){c();return}d.K=[];var e=function(){d.K&&(L(Qd,d.K),d.K=null)};Pe(a,e,3E3);b.gb.C(["initToChild"],e)}d.K?d.K.push(c):c()}else c()}
var nf=z(function(){return{Ga:null,K:[]}},P);function of(a){return(a=a.o)&&a.g("pv")&&!a.g("ar")}function pf(a,b,c){var d=a.o;d?of(a)?(b.Ga=d,c()):b.K?b.K.push(c):c():c()}function qf(a,b){return{I:function(c,d){var e=nf(b);e=F([c,e,d],pf);mf(a,b,e)},T:function(c,d){var e=c.o,f=nf(b);if(e){var g=f.K;f.Ga===e&&g&&(L(Qd,g),f.K=null)}d()}}}var rf=/^[a-z][\w.+-]+:/i;
function sf(a,b){var c=W(a),d=c.href,e=c.host,f=-1;if(!sa(b)||C(b))return d;c=b.replace(nd,"");if(-1!==c.search(rf))return c;var g=c.charAt(0);if("?"===g&&(f=d.search(/\?/),-1===f)||"#"===g&&(f=d.search(/#/),-1===f))return d+c;if(-1!==f)return d.substr(0,f)+c;if("/"===g){if(f=va(d,e),-1!==f)return d.substr(0,f+e.length)+c}else return d=d.split("/"),d[d.length-1]=c,T("/",d);return""}
function tf(a){return{I:function(b,c){var d=b.m;if(!b.o||!d)return c();var e=d["page-ref"],f=d["page-url"];e&&f!==e?d["page-ref"]=sf(a,e):delete d["page-ref"];d["page-url"]=sf(a,f).slice(0,ac.Xa);return c()}}}
var uf=[[be,1],[qf,2],[kf(),3],[function(a,b){return{I:function(c,d){var e=c.o;if(e&&(!b||b.Na)){var f=a.document.title;c.B&&c.B.title&&(f=c.B.title);var g=Oa("getElementsByTagName",a.document);"string"!==typeof f&&g&&(f=g("title"),f=(f=J(f,"0.innerHtml"))?f:"");f=f.slice(0,ac.Wa);e.l("t",f)}d()}}},4]],vf=[],wf=G(uf,Vd),xf={},yf=(xf.h=uf,xf),zf=G(yf,function(a,b,c,d){a[b]||(a[b]=[]);c&&!Aa(d)&&Vd(a[b],c,d)});wf(tf,-100);
function Af(a,b,c){b=cb(b)?b:yf[b]||uf;var d=L(fb,b);L(function(e){return d.unshift(e)},vf);return L(I(Ja([a,c]),Qd),d)}function Bf(a,b,c,d){return new S(function(e,f){if(!J(a,"navigator.onLine"))return f();var g={};g=O(d.W,(g["force-urlencoded"]=1,g));g=c+"?"+bd(g)+(d.F?"&"+d.F:"");return 2E3<g.length?f(ce("sb.tlq")):b(g)?e(""):f()})}
function Cf(a,b){var c=xe(a);if(c){var d=a.document,e=c("script");e.src=b.src;e.type=b.type||"text/javascript";e.charset=b.charset||"utf-8";e.async=b.async||!0;try{var f=d.getElementsByTagName("head")[0];if(!f){var g=d.getElementsByTagName("html")[0];f=c("head");g&&g.appendChild(f)}f.insertBefore(e,f.firstChild);return e}catch(h){}}}var Df=z(function(a){if(a=xe(a))return a("a")});function Ef(a){return(a.split(":")[1]||"").replace(/^\/*/,"").replace(/^www\./,"").split("/")[0]}
function Ff(a,b){if(!b||!b.length)return a;var c=n(a.split("#")),d=c.next().value;c=ba(c);c=(c=T("#",c))?"#"+c:"";return xa(a,"?")?d+"&"+b+c:d+"?"+b+c}function Gf(a,b,c){(c=bd(c))&&(a=Ff(a,c));b.F&&(a=Ff(a,b.F));return a}function Hf(a,b){try{delete a[b]}catch(c){a[b]=void 0}}
function If(a,b,c){return new S(function(d,e){var f="_ymjsp"+cd(a),g={};g=O((g.callback=f,g),c.W);var h=F([a,f],Hf);a[f]=function(l){try{h(),ye(k),d(l)}catch(m){e(m)}};g.wmode="5";f={};var k=Cf(a,(f.src=Gf(b,c,g),f));if(!k)return h(),e(wc("jp.s"));f=G(k,ye);f=I(f,G(ce(c.O),e));g=Ne(a,f,c.$||1E4);g=F([a,g],Oe);k.onload=g;k.onerror=I(h,g,f)})}
function Jf(a,b,c,d){var e={};e=O(d.ja?(e.wmode="7",e):{},d.W);var f=b||{signal:void 0,abort:r},g=a.fetch(Ff(c,bd(e)),{method:d.xa,body:d.F,credentials:!1===d.Fb?"omit":"include",headers:d.V,signal:f.signal}),h=G(d.O,ce);return new S(function(k,l){d.$&&Ne(a,function(){try{f.abort()}catch(m){}l(h())},d.$);return g.then(function(m){if(!m.ok){if(d.Ma)return zc(xc(m));de(d.O)}return d.Ma?m.text():d.ja?m.json():null}).then(k)["catch"](G(h(),l))})}var Kf=/[^a-z0-9.:-]/;
function Lf(a,b,c,d,e,f,g,h){if(4===b.readyState)if(200===b.status||e||g(c),e)200===b.status?f(b.responseText):g(xc(b));else{e=null;if(d)try{(e=me(a,b.responseText))||g(c)}catch(k){g(c)}f(e)}return h}
function Mf(a,b,c){var d=new a.XMLHttpRequest,e=c.F,f={},g=O(c.ja?(f.wmode="7",f):{},c.W);return new S(function(h,k){d.open(c.xa||"GET",Ff(b,bd(g)),!0);d.withCredentials=!1!==c.Fb;c.$&&(d.timeout=c.$);I(Cb,ob(function(m){var q=n(m);m=q.next().value;q=q.next().value;d.setRequestHeader(m,q)}))(c.V);var l=F([a,d,ce(c.O),c.ja,c.Ma,h,k],Lf);d.onreadystatechange=l;try{d.send(e)}catch(m){}})}
function Nf(a,b,c,d){return new S(function(e,f){var g=De(a),h=b("img"),k=I(G(h,ye),G(ce(d.O),f)),l=Ne(a,k,d.$||3E3);h.onerror=k;h.onload=I(G(h,ye),G(null,e),F([a,l],Oe));k=O({},d.W);delete k.wmode;h.src=Gf(c,d,k);Hb(a)&&(O(h.style,{position:"absolute",visibility:"hidden",width:"0px",height:"0px"}),g.appendChild(h))})}
var Of={},Pf=(Of.x={id:2,check:function(a){var b;if(b=J(a,"XMLHttpRequest"))if(b="withCredentials"in new a.XMLHttpRequest){a:{if(Kf.test(a.location.host)&&a.opera&&A(a.opera.version)&&(b=a.opera.version(),"string"===typeof b&&"12"===b.split(".")[0])){b=!0;break a}b=!1}b=!b}return b?G(a,Mf):!1}},Of.i={id:4,check:function(a){var b=xe(a);return b?F([a,b],Nf):!1}},Of);Pf.f={id:1,check:function(a){if(a.fetch){var b=J(a,"AbortController");return F([a,b?new b:void 0],Jf)}return!1}};
Pf.b={id:0,check:function(a){if(Kb(a))a=!1;else{var b=J(a,"navigator.sendBeacon");a=b&&ja("sendBeacon",b)?F([a,D(b,J(a,"navigator"))],Bf):!1}return a}};Pf.j={id:3,check:function(a){return xe(a)?G(a,If):!1}};var Qf={};function Rf(a){if(a)return H(function(b,c){var d=Pf[c];d&&b.push(d);return b},[],a)}function Sf(a){return Qf["*"]?Rf(Qf["*"]):a?Rf(Qf[a]):void 0}var Tf=["b","f","x","j","i"],Uf=["x"];Uf.unshift("f");Uf.push("j");
var Vf={},Wf=(Vf.h=Uf,Vf),Xf=z(function(a,b,c,d){(d=Sf(c)||Rf(d))||(d=Rf(c?Wf[c]:Tf));c=H(function(e,f){var g=f.check,h=f.id;(g=g(a,b))&&e.push([h,g]);return e},[],d||[]);c.length||de();return c},function(a,b,c){return c}),Yf=D(S.reject,S,ce()),Zf={},$f=(Zf.h=$d,Zf),ag=Y("g.sen",function(a,b,c){var d=Xf(a,c,b);c=Af(a,b,c);var e=$f[b],f=e?e(a,d,c):$d(a,d,c);return function(){var g=n(w(arguments)),h=g.next().value;g=ba(g);h=O(h,{H:O(void 0===h.H?{}:h.H,{O:[b]})});return f.apply(null,[h].concat(g))}},
Yf);function bg(a,b){return function(c){var d=c[a];d?(d.La=!0,d.Ka(b)):c[a]={promise:S.resolve(b),La:!0,Ka:r}}}var cg=p(function(a,b){if(!b[a]){var c,d=new S(function(e){c=e});b[a]={Ka:c,promise:d,La:!1}}return b[a].promise}),dg=z(I(Dd,ia));function eg(a,b,c){b=P(b);var d=Nc(a);c=O({ib:d(U)},c);d={};var e={};Gd(a,(e.counterKey=b,e.name="counterSettings",e.data=(d.settings=c,d),e));return dg()(bg(b,c))}function fg(a,b){var c=P(a);return dg()(cg(c)).then(b)}
var gg=z(Y("dc.init",function(){return{log:r,warn:r,error:r}}),oa);function hg(a,b,c,d){gg(a,b).log(c,d)}function ig(a,b,c,d,e){return F([a,P(b),e?[c+".p",e]:c,d],hg)}function jg(a,b,c){c=c||"as";if(a.postMessage&&!a.attachEvent){var d=Ic(a),e="__ym__promise_"+cd(a)+"_"+cd(a),f=r;f=d.C(a,["message"],X(a,c,function(g){try{var h=g.data}catch(k){return}h===e&&(f(),g.stopPropagation&&g.stopPropagation(),b())}));a.postMessage(e,"*")}else Pe(a,b,0,c)}
var kg=Y("h.p",function(a,b){var c=ag(a,"h",b),d=b.na||""+W(a).href,e=b.kb||a.document.referrer,f={},g={};f={o:Ld((f.pv=1,f)),m:(g["page-url"]=d,g["page-ref"]=e,g),B:{}};f.B.D=b.D;f.B.wa=b.wa;b.ka&&f.m&&(f.m.nohit="1");return c(f,b).then(function(h){if(h){if(!b.ka){var k={};ig(a,b,"h",(k.id=b.id,k.url=d,k.ref=e,k),b.D)()}jg(a,F([a,b,h],eg))}})["catch"](X(a,"h.g.s"))});
function lg(a,b,c){try{if(A(b)){var d=n(w(arguments));d.next();d.next();d.next();var e=ba(d);b.apply(Aa(c)?null:c,e)}}catch(f){Ne(a,G(f,zc),0)}}var mg=["yandex_metrika_callback"+da.callbackPostfix,"yandex_metrika_callbacks"+da.callbackPostfix],ng=Y("cb.i",function(a){var b=n(mg),c=b.next().value,d=b.next().value;if(A(a[c]))a[c]();"object"===typeof a[d]&&L(function(e,f){a[d][f]=null;lg(a,e)},a[d]);L(function(e){try{delete a[e]}catch(f){a[e]=void 0}},mg)});
function og(a,b){var c=Q(a).g("counters",{}),d=P(b);return c[d]}var pg=[],qg=[],rg=[],sg=[],tg=[],ug=[],vg=/^[a-zA-Z0-9'!#$%&*+-/=?^_`{|}~]+$/;function wg(a){var b=a.length;return 1>b||64<b?!1:vb(function(c){var d=c.length;if(1>d)c=!1;else if('"'===c[0]&&'"'===c[d-1]&&2<d)a:{for(d=1;d+2<c.length;d+=1){var e=c.charCodeAt(d);if(32>e||34===e||126<e){c=!1;break a}if(92===e){if(d+2===c.length||32>c.charCodeAt(d+1)){c=!1;break a}d+=1}}c=!0}else c=vg.test(c)?!0:!1;return c},a.split("."))}
function xg(a){var b=a.length;return 5>b||100<b?void 0:a}
function yg(a){var b=pd(a).replace(/^\++/gm,"").toLowerCase(),c=b.lastIndexOf("@");if(-1===c)return xg(b);a=b.substr(0,c);c=b.substr(c+1);if(!c||!wg(a))return xg(b);c=c.replace("googlemail.com","gmail.com");a:{if(b=c.match(id)){var d=n(b);d.next();b=d.next().value;if(d=d.next().value){b=Za(d,hd)?d:!1;break a}if(b){b=hd[0];break a}}b=!1}b&&(c="yandex.ru");"yandex.ru"===c?a=a.replace(ra,"-"):"gmail.com"===c&&(a=a.replace(ra,""));b=va(a,"+");-1!==b&&(a=a.slice(0,b));return xg(a+"@"+c)}
var zg=I(wa,ha(0)),Ag=fa(zg),Bg=qd(/[^\d+()]/g),Cg=/[a-z\u0430-\u044f\u0451,.]/gi;function Dg(a,b){var c=rd(b),d=c.length;if(!(Cg.test(b)||b.length-d>d||10>d||16<d)){d=c[0];var e=b[1];if("+"!==b[0]||e===d)return d=Bg(b),10>c.length||13<c.length||zg(d,"+8")?pd(b):"8"===d[0]?"7"+c.slice(1):"+"===d[0]||wb(a,+d[0])?c:"7"+c}}var Eg=z(function(a){return!!J(a,"crypto.subtle.digest")&&!!J(a,"TextEncoder")&&!!J(a,"FileReader")&&!!J(a,"Blob")});
function Fg(a,b){return new S(function(c,d){var e=(new a.TextEncoder).encode(b);a.crypto.subtle.digest("SHA-256",e).then(function(f){f=new a.Blob([f],{type:"application/octet-binary"});var g=new a.FileReader;g.onload=function(h){h=J(h,"target.result")||"";var k=va(h,",");-1!==k?c(h.substring(k+1)):d(wc("fpm.i"))};g.readAsDataURL(f)},d)})}var Gg=["yandex_cid","yandex_public_id"];
function Hg(a,b,c){c=void 0===c?0:c;b=Cb(b);b=H(function(d,e){var f=n(e),g=f.next().value;f=f.next().value;var h=Ba(f);if(!h&&(wb(a,f)&&(f=""+f),!sa(f)))return d;if(h)f=Hg(a,f,c+1);else if(!c&&Za(g,Gg))f=S.resolve(f);else{"phone_number"===g?f=Dg(a,f):"email"===g&&(f=yg(f));if(!f)return d;f=Fg(a,f)}d.push(f.then(function(k){return[g,k]}));return d},[],b);return S.all(b)}
var Ig=Y("fpm",function(a,b){if(!ld(a))return r;var c=P(b);if(!Eg(a))return hg(a,c,"ns"),r;var d=og(a,b);return d?function(e){return(new S(function(f,g){return Ba(e)?Db(e).length?f(Hg(a,e).then(function(h){if(h&&h.length){var k={},l={};d.params((l.__ym=(k.fpp=h,k),l))}},r)):g(ce("fpm.l")):g(ce("fpm.o"))}))["catch"](X(a,"fpm.en"))}:r});
function Jg(a,b){return H(function(c,d){var e=n(d),f=e.next().value,g=e.next().value;e=g;g=Ba(g);if(!g&&(wb(a,e)&&(e=""+e),!sa(e)))return c;e=g?Jg(a,e):e;Ma(e)&&c.push([f,e]);return c},[],Cb(b))}function Kg(a,b){return function(c){var d=og(a,b);if(d){var e=gg(a,P(b));if(Ba(c))if(Ma(Db(c))){if((c=Jg(a,c))&&Ma(c)){e={};var f={};d.params((f.__ym=(e.fpmh=c,e),f))}}else e.log("fpeo");else e.log("fpno")}}}function Lg(a){a=Q(a);var b=a.g("dsjf")||ia({});a.Z("dsjf",b);return b}
function Mg(a,b,c){Lg(a)(function(d){d[b]=O(d[b]||{},c)})}function Ng(a,b){Lg(a)(function(c){delete c[b]})}function Og(a,b){return function(c){Mg(a,b,c)}}
var Pg=p(function(a,b){var c={};Lg(a)(function(d){c=d[b]||{}});return c}),Qg=Y("c.c.cc",function(a){var b=Q(a),c=I(Pg(a),function(d){var e={};e=(e.clickmap=!!d.clickmap,e);return O({},d,e)});return X(a,"g.c.cc",I(D(b.g,b,"counters",{}),Db,ob(c)))}),Rg=Y("gt.c.rs",function(a,b){var c=P(b),d=b.id,e=b.G,f=b.Lb,g=b.Vb,h=F([a,c],Ng),k={};Mg(a,c,(k.id=d,k.type=+e,k.clickmap=f,k.trackHash=!!g,k));return h}),Sg=z(Ed);
function Tg(a,b){return{I:function(c,d){var e=(c.B||{}).D,f=void 0===c.H?{}:c.H;if(e&&!f.F&&c.o&&c.m){var g=ne(a,e),h=Sg(a),k=c.o.g("pv");if(g&&!c.m.nohit){var l={},m={};Gd(a,(m.counterKey=P(b),m.name="params",m.data=(l.val=e,l),m));k?encodeURIComponent(g).length>ac.Va?h.push([c.o,e]):c.m["site-info"]=g:(f.F=g,c.H=f,c.ha||(c.ha={}),c.ha.sb=!0)}}d()},T:function(c,d){var e=Sg(a),f=og(a,b),g=f&&f.params;g&&(f=Va(I(fb,ha(c.o)),e),L(function(h){var k=n(h);k.next();k=k.next().value;g(k);h=eb(a)(h,e);e.splice(h,
1)},f));d()}}}function Ug(a,b,c,d,e){var f=F([a,d,e],lg);return c.then(f,function(g){f();ge(a,b,g)})}var Vg=z(Dd,P);function Wg(a){var b=r,c=null,d=a.length;if(0!==a.length&&a[0]){var e=a.slice(-1)[0];A(e)&&(b=e,d=a.length+-1);var f=a.slice(-2)[0];A(f)&&(b=f,c=e,d=a.length+-2);d=a.slice(0,d);return{fb:c,ba:b,D:1===d.length?a[0]:Na(d)}}}
var Xg=Y("pa.int",function(a,b){var c={};return c.params=function(){var d=w(arguments),e=Wg(d);if(!e)return null;d=e.fb;var f=e.D;e=e.ba;if(!Ba(f)&&!cb(f))return null;var g=ag(a,"1",b),h=Vg(b).url,k=!fd(b),l="pa",m={};m=(m.id=b.id,m);var q=f,y="";if(y=J(f,"__ym.user_id"))l="pau",m.uid=y;Za("__ymu",Db(f))&&(l="paup");q.__ym&&(q=O({},f),q.__ym=H(function(B,x){var v=J(f,"__ym."+x);v&&(B[x]=v);return B},{},ie),Db(q.__ym).length||delete q.__ym,k=!!Db(q).length);q=y?void 0:ne(a,q);l=ig(a,b,l,m,q);m={};
q={};g=g({B:{D:f},o:Ld((m.pa=1,m.ar=1,m)),m:(q["page-url"]=h||W(a).href,q)},b).then(k?l:r);return Ug(a,"p.s",g,e,d)},c});function Yg(a,b,c){var d=!0;c=void 0===c?r:c;d=void 0===d?!1:d;var e=Se(a);if(b&&A(b.push)){var f=b.push;b.push=function(){var g=w(arguments),h=n(g).next().value;d&&e.M(h);g=f.apply(b,g);d||e.M(h);return g};c({ub:e,unsubscribe:function(){b.push=f}});L(e.M,b)}}var Zg=Y("guid.int",function(a,b){var c={};return c.getClientID=function(d){var e=Me(a,b);d&&lg(a,d,null,e);return e},c});
function $g(a,b){var c={};c=(c.string=!0,c.object=!0,c["boolean"]=b,c)[typeof b]||!1;var d={};a((d.trackLinks=c,d))}
function ah(a,b,c){var d=Ld();void 0!==c.da&&d.l("ite",Ra(c.da));c.ca&&d.l("dl",1);c.U&&d.l("ln",1);var e=c.Ta||{},f={};d={o:d,B:{title:e.title||c.title,fa:!!c.fa,D:e.params},m:(f["page-url"]=c.url,f["page-ref"]=b.na||W(a).href,f)};f="Link";c.ca?f=c.U?"Ext link - File":"File":c.U&&(f="Ext link");var g={},h={};Gd(a,(h.counterKey=P(b),h.name="event",h.data=(g.schema="Link click",g.name=(c.U?"external":"internal")+" url: "+c.url,g),h));g={};b=c.sender(d,b).then(ig(a,b,"lcl",(g.prefix=f,g.id=b.id,g.url=
c.url,g),c.Ta));Ug(a,"cl.p.s",b,e.callback||r,e.ctx)}
function bh(a,b){if(a.Bb()){var c=null;try{c=b.target||b.srcElement}catch(B){}if(c){3===c.nodeType&&(c=c.parentNode);for(var d=c&&c.nodeName&&(""+c.nodeName).toLowerCase();J(c,"parentNode.nodeName")&&("a"!==d&&"area"!==d||!c.href&&!c.getAttribute("xlink:href"));)d=(c=c.parentNode)&&c.nodeName&&(""+c.nodeName).toLowerCase();c=c.href?c:null}else c=null;var e=c;if(e&&!ze("ym-disable-tracklink",e)){c=a.J;d=a.cb;var f=a.eb,g=a.sender,h=a.hb;var k=f.na;var l=e.href;var m=pd(e.innerHTML&&e.innerHTML.replace(/<\/?[^>]+>/gi,
""));m||(m=(m=e.querySelector("img"))?pd(m.getAttribute("title")||m.getAttribute("alt")):"");m=l===m?"":m;var q=J(b,"isTrusted");if(ze("ym-external-link",e))ah(c,f,{url:l,U:!0,title:m,da:q,sender:g});else{if(k){var y=Df(c);y?(y.href=k,k=y.hostname,y.search.replace(/^\?/,"")):k=void 0}else k=W(c).hostname;h=RegExp("\\.("+T("|",L(ya,h))+")$","i");y=e.protocol+"//"+e.hostname+e.pathname;h=ke.test(y)||ke.test(l)||h.test(l)||h.test(y);e=e.hostname;jd(k)===jd(e)?h?ah(c,f,{url:l,ca:!0,da:q,title:m,sender:g}):
m&&d.l("il",pd(m).slice(0,100)):l&&je.test(l)||ah(c,f,{url:l,fa:!0,U:!0,ca:h,da:q,title:m,sender:g})}}}}var ch=p(function(a,b){sa(b)?a.push(b):L(I(u,D(a.push,a)),b)}),dh=dd("retryReqs",function(a){var b=ue(a),c=b.g("retryReqs",{}),d=V(a)(U);L(function(e){var f=n(e);e=f.next().value;f=f.next().value;(!f||!f.time||f.time+864E5<d)&&delete c[e]},Cb(c));b.l("retryReqs",c);return c},!0);function eh(a){var b=dh(a);ue(a).l("retryReqs",b)}
function fh(a,b){var c=dh(a);b.o&&!za(c)&&b.B&&(delete c[b.B.Y],eh(a))}function gh(a,b){return{I:function(c,d){var e=c.o,f=c.m,g=void 0===c.H?{}:c.H;if(e&&f){var h=V(a);e.Oa("rqnl",1);for(var k=dh(a),l=1;k[l];)l+=1;c.B||(c.B={});c.B.Y=l;var m={};k[l]=(m.protocol=ac.Ca,m.host=Zb,m.resource=c.ia.P,m.postParams=g.F,m.time=h(U),m.counterType=b.G,m.params=f,m.browserInfo=e.J(),m.counterId=b.id,m.ghid=Je(a),m);eh(a)}d()},T:function(c,d){fh(a,c);d()}}}
var hh=[Ag("watch"),Ag("clmap")],ih=Y("g.r",function(a){var b=V(a),c=dh(a),d=b(U),e=Je(a);return H(function(f,g){var h=n(g),k=h.next().value;(h=h.next().value)&&sb(ia(h.resource),hh)&&!h.d&&h.ghid&&h.ghid!==e&&h.time&&500<d-h.time&&h.time+864E5>d&&2>=h.browserInfo.rqnl&&(h.d=1,k={protocol:h.protocol,host:h.host,P:h.resource,xb:h.postParams,D:h.params,ab:h.browserInfo,Mb:h.ghid,time:h.time,Y:xb(k),bb:h.counterId,G:h.counterType},f.push(k));return f},[],Cb(c))});
function jh(a,b,c){function d(){B||(y=!0,x=!1,B=!0,f())}function e(){m=!0;k(!1);b()}function f(){Oe(a,l);if(m)k(!1);else{var N=Math.max(0,c-(x?v:v+q(U)-M));N?l=Pe(a,e,N,"u.t.d.c"):e()}}function g(){x=y=B=!0;v+=q(U)-M;M=q(U);f()}function h(){y||B||(v=0);M=q(U);y=B=!0;x=!1;f()}function k(N){N=N?E.C:E.ua;N(a,["blur"],g);N(a,["focus"],h);N(a.document,["click","mousemove","keydown","scroll"],d)}var l=0,m=!1;if(Pb(a))return l=Pe(a,b,c,"u.t.d"),F([a,l],Oe);var q=V(a),y=!1,B=!1,x=!0,v=0,M=q(U),E=Ic(a);k(!0);
f();return function(){Oe(a,l);k(!1)}}
var kh=Y("nb.p",function(a,b){function c(v){h()||(v="number"===typeof v?v:15E3,x=jh(a,d(!1),v),l())}function d(v){return function(M){var E={};M=void 0===M?(E.ctx={},E.callback=r,E):M;if(v||!y&&!g.qb){y=!0;l();x&&x();var N=m(U);E=(xb(g.g("lastHit"))||0)<N-18E5;var kb=.1>Math.random();g.l("lastHit",N);N={};N=Ld((N.nb=1,N.cl=B,N.ar=1,N));var Gc=Vg(b),Be={};N={m:(Be["page-url"]=Gc.url||W(a).href,Be),o:N,B:{force:v}};Gc=gg(a,P(b)).warn;!M.callback&&M.ctx&&Gc("nbnc");(E=v||E||kb)||(E=a.location.href,kb=
a.document.referrer,E=!(E&&kb?Ef(E)===Ef(kb):!E&&!kb));if(E)return E=e(N,b),Ug(a,"l.o.l",E,M.callback,M.ctx)}return null}}var e=ag(a,"n",b),f=P(b),g=ve(a,b.id),h=G(G(f,Pg(a)),I(Qd,K("accurateTrackBounce"))),k={},l=G((k.accurateTrackBounce=!0,k),Og(a,f)),m=V(a),q=m(U),y=!1,B=0,x;fg(b,function(v){B=v.ib-q});b.Aa&&c(b.Aa);f={};f=(f.notBounce=d(!0),f.u=x,f);f.accurateTrackBounce=c;return f});function lh(a,b){if(!b||!b.querySelectorAll)return[];var c=b.querySelectorAll(a);return c?db(c):[]}
function mh(a,b,c){if(!(b&&b.Element&&b.Element.prototype&&b.document&&c))return null;if(b.Element.prototype.closest&&ja("closest",b.Element.prototype.closest)&&c.closest)return c.closest(a);var d=Ae(b);if(d){for(b=c;b&&1===b.nodeType&&!d.call(b,a);)b=b.parentElement||b.parentNode;return b&&1===b.nodeType?b:null}d=J(b,"Element.prototype.querySelectorAll");if(ja("querySelectorAll",d)&&b.document.querySelectorAll){for(a=db((b.document||b.ownerDocument).querySelectorAll(a));c&&1===c.nodeType&&-1===ma(b)(c,
a);)c=c.parentElement||c.parentNode;return c&&1===c.nodeType?c:null}return null}var nh=z(function(){for(var a=59,b={},c=0;c<he.length;c+=1)b[he[c]]=String.fromCharCode(a),a+=1;return b}),oh=Y("trigger.in",function(a,b){b.Sa&&jg(a,F([a,"yacounter"+b.id+"inited"],Ee),"t.i")}),ph={},qh={},rh={i:"id",n:"name",h:"href",ty:"type"};qh.h=!0;qh.c=!0;
var sh={p:function(a,b,c){var d;if(d=b)d=La(b,"isConnected")?!b.isConnected:mh("html",a,b)!==a.document.documentElement;if(d&&b._ymp)return b._ymp;var e="";d=b;for(var f=nh(),g=Fe(d)||"*";d&&d.parentNode&&!Za(g,["BODY","HTML"]);){e+=f[g]||"*";a:{g=d;var h=c;var k=a;var l=g,m=J(k,"document");if(k=l&&l!==m.documentElement?l===Ce(k)?m.documentElement:J(l,"parentNode"):null){k=k.childNodes;l=g&&g.nodeName;for(var q=m=0;q<k.length;q+=1)if(l===(k[q]&&k[q].nodeName)){if(g===k[q]){g=m;break a}h&&k[q]===h||
(m+=1)}}g=0}e+=g||"";d=d.parentElement;g=Fe(d)||"*"}a=pd(e,128);b&&(b._ymp=a);return a},cs:function(a,b){function c(){var l=d();return 1===lh(l,g).length?l:null}function d(){var l=T("",h);return e?l+" "+e:l}for(var e="",f=b,g=Ce(a),h=[];f&&f.parentElement;){if(f.id){h.push("#"+f.id);var k=c();if(k)return k}if(f.classList.length&&(L(function(l){return h.push("."+l)},pa(f.classList)),k=c()))return k;h.length&&(e=d());h=[];f=f.parentElement}return null},c:function(a,b,c){(a=pd(J(b,"textContent")))&&
c&&(c=c(b),c.length&&sb(I(K("textContent"),pd,ha(a)),c)&&(a=""));He(b)&&(a=pd(b.getAttribute&&b.getAttribute("value")||a));return a}};function th(a,b,c,d,e){return H(function(f,g){var h=null;g in rh?h=b.getAttribute&&b.getAttribute(rh[g]):g in sh&&(h="p"===g?sh[g](a,b,e):"c"===g?sh[g](a,b,d):sh[g](a,b));if(h){h=h.slice(0,ph[g]||100);if(qh[g]){h=""+h;for(var k=2166136261,l=h.length,m=0;m<l;m+=1)k^=h.charCodeAt(m),k+=(k<<1)+(k<<4)+(k<<7)+(k<<8)+(k<<24);h=""+(k>>>0)}f[g]=h}return f},{},c)}
var uh=G("form",mh),vh=G("form",lh);function wh(a,b,c){return th(a,b,["i","n","p"],void 0,c)}function xh(a,b,c,d){return function(){if(og(a,b)){var e=w(arguments);return d.apply(null,ca(e))}}}var yh="button,"+T(",",L(function(a){return'input[type="'+a+'"]'},["button","submit","reset","file"]))+",a";function zh(a,b){var c=mh(yh,a,b);if(!c){var d=mh("div",a,b);d&&(lh(yh+",div",d).length||(c=d))}return c}var Ah=G(yh,lh),Bh={},Ch=(Bh.A="h",Bh.BUTTON="i",Bh.DIV="i",Bh.INPUT="ty",Bh);
function Dh(a,b,c){var d=Fe(b);return d&&th(a,b,Wa(["p",Ch[d],"c"]),Ah,c)}var Eh=z(function(a){a=W(a);a=ad(a.search.substring(1));return{id:xb(a["_ym_status-check"]||""),lang:a._ym_lang||"ru"}});function Fh(a){var b=Eh(a).id;a=Q(a).g("getCounters",Ed)();a=L(K("id"),a);var c={};return c.id=b,c.counterFound=!!b&&Za(b,a),c}var Gh=G("div,span,main,section,p,b,h1,h2,h3,h4,h5,h6,td,small,a,i,td,li,q",mh),Hh=G("div,span,main,section,p,b,h1,h2,h3,h4,h5,h6,td,small,a,i,td,li,q",lh);
function Ih(a,b,c){return th(a,b,["p","cs"],void 0,c)}
function Jh(a,b){var c=xe(a);if(c){var d=c("div"),e=De(a);if(e){d.innerHTML='<iframe name="RemoteIframe" allowtransparency="true" style="position: absolute; left: -999px; top: -999px; width: 1px; height: 1px;"></iframe>';var f=d.firstChild;f.onload=function(){var h=c("meta");h.setAttribute("http-equiv","Content-Security-Policy");h.setAttribute("content","script-src *");f.contentWindow.document.head.appendChild(h);Cf(f.contentWindow,{src:b})};a._ym__remoteIframeEl=f;e.appendChild(d);d.removeChild(f);
var g=null;d.attachShadow?g=d.attachShadow({mode:"open"}):d.createShadowRoot?g=d.createShadowRoot():d.webkitCreateShadowRoot&&(g=d.webkitCreateShadowRoot());g?g.appendChild(f):(e.appendChild(f),a._ym__remoteIframeContainer=f)}}}
var Kh=/^http:\/\/([\w\-.]+\.)?webvisor\.com\/?$/,Lh=/^https:\/\/([\w\-.]+\.)?metri[kc]a\.yandex\.(ru|by|kz|com|com\.tr)\/?$/,Mh=Fa(/^https:\/\/(yastatic\.net\/s3\/metrika|s3\.mds\.yandex\.net\/internal-metrika-betas|[\w-]+\.dev\.webvisor\.com|[\w-]+\.dev\.metrika\.yandex\.ru)\/(\w|-|\/|(\.)(?!\.))+\.js$/),Nh=["form","button","status"];
function Oh(a,b){var c=b.lang;c=void 0===c?"":c;var d=b.appVersion;d=void 0===d?"":d;var e=b.fileId;e=void 0===e?"":e;var f=b.beta;f=void 0===f?!1:f;d=T(".",Va(p(wb)(a),L(I(u,xb),d.split("."))));if(!Za(e,Nh)||!Za(c,["ru","en","tr"]))return"";c=(f?"https://s3.mds.yandex.net/internal-metrika-betas":"https://yastatic.net/s3/metrika")+(d?"/"+d:"")+"/form-selector/"+(e+"_"+c+".js");return Mh(c)?c:""}
function Ph(a,b,c,d){c=void 0===c?"":c;var e=Q(a),f={};f.getCachedTags=nh;var g={};f.form=(g.closest=G(a,uh),g.select=vh,g.getData=G(a,wh),g);d&&(d={},f.block=(d.closest=G(a,Gh),d.select=Hh,d.getData=G(a,Ih),d));d={};f.button=(d.closest=G(a,zh),d.select=Ah,d.getData=G(a,Dh),d);d={};f.status=(d.checkStatus=F([a,xb(c)],Fh),d);e.l("_u",f);b&&Cf(a,{src:b})}
var Qh=[],Rh=z(function(a,b,c){L(I(Ja([a,b,c]),Qd),Qh);c.inline?(b=Oh(a,c),Ph(a,b,void 0===c.id?"":c.id,c.isBlockUtilsEnabled)):c.resource&&Mh(c.resource)&&(a._ym__postMessageEvent=b,a._ym__inpageMode=c.inpageMode,a._ym__initMessage=c.initMessage,Jh(a,c.resource))},function(a,b,c){return c.id});function Sh(a,b){var c=J(b,"origin");c&&(Kh.test(c)||Lh.test(c))&&(c=me(a,b.data),"appendremote"===J(c,"action")&&Rh(a,b,c))}
var Th=Y("cs.init",function(a,b){var c=Eh(a),d=c.id;c=c.lang;if(d&&b.id===d&&"0"===b.G){var e={};c=Oh(a,(e.lang=c,e.fileId="status",e));Pe(a,F([a,c,""+d],Ph),0,"cs")}}),Uh=Y("suid.int",function(a,b){var c={};return c.setUserID=function(d,e,f){if(sa(d)||wb(a,d)){var g=og(a,b);d=Na(["__ym","user_id",d]);g.params(d,e||r,f)}else gg(a,P(b)).error("wuid")},c}),Vh=Y("up.int",function(a,b){var c={};return c.userParams=X(a,"up.c",function(d,e,f){var g=og(a,b),h=gg(a,P(b)).warn;g?Ba(d)?(h={},d=(h.__ymu=d,h),
(g=g.params)&&g(d,e||r,f)):h("wup"):h("nci")}),c});function Wh(a,b){return{I:function(c,d){of(c)?d():fg(b,function(e){if(e=J(e,"settings.hittoken")){var f={};e=(f.hittoken=e,f);c.m=O(c.m||{},e)}d()})}}}var Xh=z(Dd,P),Yh=Y("fpi",function(a){var b=Jc(a);if(b&&!a.document.hidden){var c=Q(a).Z;c("fpe",1);var d=Ic(a).C(a,["visibilitychange","webkitvisibilitychange"],function(){a.document.hidden&&(c("fht",b.now()),d())})}}),Zh={},$h=z(Dd),ai,bi=/counterID=(\d+)/;ai=D(bi.exec,bi);
var ci=I(ai,K("1")),di=p(function(a,b){var c=db(b),d=n(c),e=d.next().value,f=ba(d);d=""+e;var g=ci(d);g?d={id:g,G:"0"}:-1===va(d,":")?d=(d=xb(d))?{id:d,G:"0"}:void 0:(g=n(d.split(":")),d=g.next().value,g=g.next().value,d=(d=xb(d))?{id:d,G:bc(g)?"1":"0"}:void 0);g=a.Ya[ac.Da];if(d){var h=n(c);h.next();f=h.next().value;h=ba(h);if(f){var k=og(a,d),l=P(d),m=$h(a);m[l]||(m[l]={});l=m[l];if(!b.Fa){if(m=Zh[f])for(var q=0;q<m.length;q+=1)if((0,m[q])(a,d,h,k))return;"init"===f?(b.Fa=!0,k?(c={},hg(a,""+e,"dc",
(c.key=e,c))):a["yaCounter"+d.id]=new g(O({},h[0],d))):k&&k[f]&&l.ob?(k[f].apply(k,ca(h)),b.Fa=!0):(e=l.Pa,e||(e=[],l.Pa=e),e.push(c))}}}else A(g[e])&&g[e].apply(g,ca(f))}),ei=[],fi=!1,gi=!1;function hi(a){if(ei.length){var b=ei.shift();gi?b():Pe(a,b,100)}else fi=!1}
function ii(a,b,c){c=void 0===c?1:c;var d=void 0===d?Vc:d;gi=Infinity===c;return ia(function(e,f){function g(){try{var k=b(d(a,c));h=h.concat(k)}catch(l){return e(l)}b(Sc);if(b(Pc))return f(h),hi(a);gi?(b(d(a,1E4)),f(h),hi(a)):Pe(a,g,100)}var h=[];fi?ei.push(g):(fi=!0,g())})}function ji(a,b,c,d,e){d=void 0===d?1:d;e=void 0===e?"itc":e;b=Xc(b,c);ii(a,b,d)(Qe(X(a,e),r))}
var ki=Y("destruct.e",function(a,b,c){return function(){var d=Q(a),e=b.id;L(function(f,g){return A(f)&&X(a,"dest.fr."+g,f)()},c);delete d.g("counters")[P(b)];delete a["yaCounter"+e]}});function li(a,b,c,d){return function(){var e=w(arguments);e=d.apply(null,ca(e));return C(e)?og(a,b):e}}function mi(a,b,c,d){return X(a,"cm."+c,d)}function ni(a,b,c,d,e){if(!c.length)return e;c=L(function(f){return F([a,b,d],f)},c);return I.apply(null,ca(c))(e)}var oi=z(Dd,P),pi=Q(window);pi.Z("hitParam",{});
rg.push(function(a,b){var c={};return c.firstPartyParams=Ig(a,b),c.firstPartyParamsHashed=Kg(a,b),c});ie.push("fpp");ie.push("fpmh");(function(){var a=Q(window);a.Z("getCounters",Qg(window));qg.push(Rg);tg.push(function(b,c){c.counters=a.g("getCounters")})})();$f["1"]=$d;rg.push(Xg);Wf["1"]=Tf;wf(Tg,-1);yf["1"]=[[Tg,-1],[be,1],[qf,2],[kf(),3],[tf,4]];
rg.push(Y("p.ar",function(a,b){var c=ag(a,"a",b),d={};return d.hit=function(e,f,g,h,k,l){var m={};m={m:{},o:Ld((m.pv=1,m.ar=1,m))};f=Ba(f)?{title:f.title,Ja:f.referer,D:f.params,ba:f.callback,J:f.ctx}:{title:f,Ja:g,D:h,ba:k,J:l};h=Vg(b);g=e||W(a).href;h.url!==g&&(h.ref=h.url,h.url=e);e=f.Ja||h.ref||a.document.referrer;h={};h=ig(a,b,"pv",(h.id=b.id,h.url=g,h.ref=e,h),f.D);k=O(m.B||{},{D:f.D,title:f.title});l={};m=c(O(m,{B:k,m:O(m.m||{},(l["page-url"]=g,l["page-ref"]=e,l))}),b).then(h);return Ug(a,
"p.ar.s",m,f.ba||r,f.J)},d}));$f.a=$d;yf.a=uf;Wf.a=Tf;rg.push(Zg);
rg.push(Y("cl.p",function(a,b){function c(q,y,B,x){x=void 0===x?{}:x;B?ah(a,b,{url:B,U:!0,ca:q,fa:y,sender:d,Ta:x}):g.warn("clel")}var d=ag(a,"2",b),e=[],f=P(b),g=gg(a,f),h=X(a,"s.s.tr",G(Og(a,f),$g));f={J:a,eb:b,hb:e,sender:d,Nb:Q(a),cb:ve(a,b.id),Ob:Je(a),Bb:G(G(f,Pg(a)),I(Qd,K("trackLinks")))};f=X(a,"cl.p.c",G(f,bh));f=Ic(a).C(a,["click"],f);b.Ra&&h(b.Ra);var k=X(a,"file.clc",F([!0,!1],c)),l=X(a,"e.l.l.clc",F([!1,!0],c));e=X(a,"add.f.e.clc",ch(e));var m={};return m.file=k,m.extLink=l,m.addFileExtension=
e,m.trackLinks=h,m.u=f,m}));yf["2"]=uf;$f["2"]=$d;Wf["2"]=Tf;$f.r=Zd("r");Wf.r=["f","x","j","i"];sg.push(Y("p.r",function(a,b){var c=ih(a),d=ag(a,"r",b),e=X(a,"rts.p");return fg(b,F([function(f,g){var h={id:g.bb,G:g.G},k={H:{F:g.xb},o:Ld(g.ab),m:g.D,B:{Y:g.Y},ia:{P:g.P}};h=d(k,h)["catch"](e);return f.then(G(h,u))},S.resolve(),c],H)).then(G(void 0,u))["catch"](e)}));
zf("r",function(a){return{I:function(b,c){var d=void 0===b.o?Ld():b.o,e=b.B.Y,f=dh(a),g=d.g("rqnl",0)+1;d.l("rqnl",g);if(d=J(f,T(".",[e,"browserInfo"])))d.rqnl=g,eh(a);c()},T:function(b,c){fh(a,b);c()}}},1);wf(gh,100);zf("1",gh,100);zf("n",gh,100);rg.push(kh);zf("n",be,1);zf("n",qf,2);zf("n",kf(),3);zf("n",tf,3);$f.n=$d;Wf.n=Tf;O(ec,{Aa:{ra:"accurateTrackBounce"}});rg.push(oh);sg.push(Th);rg.push(Uh);ie.push("user_id");rg.push(Vh);
wf(function(a,b){return{T:function(c,d){var e=og(a,b);e=e&&e.userParams;var f=(c.B||{}).wa;e&&f&&e(f);d()}}},0);ug.push(function(a){var b=Q(a);b.g("i")||(b.l("i",!0),Ic(a).C(a,["message"],G(a,Sh)))});wf(Wh,20);zf("n",Wh,20);zf("1",Wh,20);ug.unshift(Yh);
hf.fp=function(a,b,c){if(c.m&&c.m.nohit)return null;c=Q(a).g;if(!c("fpe"))return null;b=Xh(b);if(b.jb)return null;c=c("fht",Infinity);a:{var d=J(a,"performance.getEntriesByType");if(A(d)){if(a=Va(I(u,K("name"),ha("first-contentful-paint")),d.call(a.performance,"paint")),a.length){a=a[0].startTime;break a}}else{var e=J(a,"chrome.loadTimes");d=ff(a);if(A(e)&&(e=e.call(a.chrome),e=J(e,"firstPaintTime"),d&&e)){a=1E3*e-d;break a}if(a=J(a,"performance.timing.msFirstPaint")){a-=d;break a}}a=void 0}return a&&
c>a?(b.jb=a,Math.round(a)):null};rg.push(function(a,b){var c=$h(a),d=P(b),e=c[d];e||(e={},c[d]=e);e.ob=!0;if(c=e.Pa)d=di(a),L(d,c)});
function qi(a,b,c,d){var e=this;return X(window,"c.i",function(){function f(v){(v=xh(k,m,"",v)(k,m))&&(A(v.then)?v.then(g):g(v));return v}function g(v){v&&(A(v)?q.push(v):Ba(v)&&L(function(M){var E=n(M);M=E.next().value;E=E.next().value;A(E)&&("u"===M?q.push(E):h(E,M))},Cb(v)))}function h(v,M,E){e[M]=ni(k,m,E||y,M,v)}var k=window;(!k||isNaN(a)&&!a)&&de();var l=cc(a,b,c,d),m=dc(l);oi(m).Rb=l;var q=[],y=[mi,xh,li],B=L(u,sg);l=P(m);m.id||zc(wc("Invalid Metrika id: "+m.id,!0));var x=pi.g("counters",{});
if(x[l])return B={},hg(k,l,"dc",(B.key=l,B)),x[l];x[l]=e;pi.l("counters",x);pi.Z("counter",e);L(function(v){v(k,m)},pg);L(f,qg);f(kg);h(ki(k,m,q),"destruct",[mi,li]);jg(k,F([k,B,f,1,"a.i"],ji));L(f,rg);l={};Gd(k,(l.counterKey=P(m),l.name="counter",l.data=Ud(m),l))})()}L(fa(Qd)(window),ug);if(window.Ya&&qi){var ri=ac.Da;window.Ya[ri]=qi;ng(window);L(I(Ja([window,window.Ya[ri]]),Qd),tg)}(function(a){var b=J(a,"ym");if(b){var c=J(b,"a");c||(b.a=[],c=b.a);var d=di(a);Yg(a,c,function(e){e.ub.C(d)})}})(window);}).call(this)
